current_version = "0.2.0"

[[files]]
path = "example.txt"
search = "version = '{{current_version}}'"
replace = "version = '{{new_version}}'"

[[files]]
path = "example.py"
search = "__version__ = \"{{current_version}}\""
replace = "__version__ = \"{{new_version}}\""
