current_version = "0.1.0"

[[files]]
path = "example.txt"
regex = true
search = """
version = '{{current_version}}'
hello (?<name>.+)
"""
replace = """
version = '{{new_version}}'
hello
from $name
"""
