name: 'Check as aqua custom registry'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'registry.yaml'
      - 'aqua/**.yaml'
  workflow_dispatch:

jobs:
  validate-registry:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.43.1
