name: 'Deployment document'

on:
  workflow_call:
  workflow_dispatch:

env:
  TASK_X_REMOTE_TASKFILES: 1

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        with:
          aqua_version: v2.43.1
      - name: Configure venv
        run: |
          uv sync --frozen --no-dev
      - name: Build doc
        run: |
          task --yes docs:build-dirhtml
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs/_build/dirhtml --project-name=${{ secrets.CLOUDFLARE_PAGES_NAME }} --branch=main
