name: 'Deployment document'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Configure venv
        run: |
          uv sync --frozen --no-dev
      - name: Build doc
        run: |
          uv run make -C docs dirhtml
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs/_build/dirhtml --project-name=${{ secrets.CLOUDFLARE_PAGES_NAME }} --branch=main
