name: 'Run CI jobs (for Nim-lang implements)'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: './_nim'

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      # TODO: Find lint tools
  test:
    needs: ['lint']
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        nim-version:
          - '2.0.0'
          - '2.0.14'
          - '2.2.0'
          - '2.2.2'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Cache Nim resources'
        id: cache_nim
        uses: actions/cache@v4
        with:
          path: |
            ~/.choosenim
            ~/.nimble
          key: 'nimcaches_ubuntu-latest_${{ matrix.nim-version }}'
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '${{ matrix.nim-version }}'
      - name: 'Run unittests'
        run: |
          nimble test -Y
  e2e:
    needs: ['lint']
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        nim-version:
          - '2.0.0'
          - '2.2.2'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Cache Nim resources'
        id: cache_nim
        uses: actions/cache@v4
        with:
          path: |
            ~/.choosenim
            ~/.nimble
          key: 'nimcaches_${{ matrix.os }}_${{ matrix.nim-version }}'
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '${{ matrix.nim-version }}'
      - name: 'Build executable'
        run: |
          nimble build -Y
      # TODO: Write after implements
