name: 'Release binaries'

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Emulate version (require "v" prefix)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.vm }}
    env:
      package_name: 'age-${{ inputs.version || github.ref_name }}'
      dist_name: 'age-${{ inputs.version || github.ref_name }}_${{ matrix.os_name }}_${{ matrix.cpu_name }}'
    strategy:
      matrix:
        include:
          - vm: ubuntu-latest
            os_name: 'linux'
            cpu_name: 'x86-64'
          - vm: macos-latest
            os_name: macos
            cpu_name: 'arm64'
          - vm: windows-latest
            os_name: windows
            cpu_name: 'x86-64'
    steps:
      - uses: 'actions/checkout@v4'
      - name: Cache Nim resources
        id: cache_nim
        uses: actions/cache@v4
        with:
          path: |
            ~/.choosenim
            ~/.nimble
          key: nimcaches--${{ matrix.vm }}
      - uses: 'jiro4989/setup-nim-action@v2'
        with:
          nim-version: '2.2.4'
      - name: 'Build and bundle'
        run: |
          nimble build -d:release -Y
          nimble bundle
      - name: 'Make archive'
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          directory: 'dist'
          path: '${{ env.package_name }}'
          filename: '${{ env.dist_name }}.zip'
      - uses: actions/upload-artifact@v4
        with:
          name: 'release-${{ env.dist_name }}'
          path: 'dist/${{ env.dist_name }}.zip'
  release:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: 'actions/checkout@v4'
      - uses: actions/download-artifact@v4
        with:
          path: 'dist'
          merge-multiple: true
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*'
          bodyFile: '.github/release-body.md'
          draft: false
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref }}
          prerelease: false
  deploy-doc:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    needs: [build]
    uses: './.github/workflows/deploy-doc.yml'
    secrets: inherit
